FEDERATION_SERVER="https://api.stellar.org/federation" 

[DOCUMENTATION] 
ORG_NAME="Dinar Token" 
ORG_URL="https://dinar.toml.host" 
ORG_LOGO="https://dinar.toml.host/logo.png"

[[CURRENCIES]] 
name="Dinar Token" 
code="DINAR" 
desc="Dinar Token (Asset Code : DINAR) brings real Dinar coin into blockchain. Every DINAR equivalent with 4.25 grams of real physical gold. The purity of gold is 99.99999% or 24 carat." 
conditions="Buy DINAR to save your assets over blockchain for medium and long term investments and get 2.5% monthly yields for 10 years." 
issuer="GA3MPEPAUFFLBRP4DTTGTK76ZVQYZOBXOSJD7S4VBIYSU7BL3OKDINAR" 
display_decimals=7 
image="https://dinar.toml.host/logo.png"
